```{r}
library(tidyverse)
```

```{r}
UNESCO <- read_csv('../data/UNESCO-2011.csv')
```

```{r}
UN <- read_csv('../data/UN-data.csv')
```
```{r}
UN <- UN %>% 
  filter(Year == 2010)
```


```{r}
UNESCO <- UNESCO %>% 
  mutate(Country = strsplit(Country, ",")) %>% 
  unnest(Country)
```

```{r}
GDP <-
  UN %>% 
  filter(topic == 'GDP per capita (US dollars)' & Series == 'GDP per capita (US dollars)') %>%
  select(Country, country_GDP_per_capita_US_dollars = Value)
```

```{r}
RD <-
  UN %>% 
  filter(topic == 'domestic expenditure in RD' & Series == 'Gross domestic expenditure on R & D: as a percentage of GDP (%)') %>% 
  select(Country, country_RD_exp_as_GDP_percentage = Value)
```

```{r}
CO2 <-
  UN %>% 
  filter(topic == 'CO2 emission' & Series == 'Emissions per capita (metric tons of carbon dioxide)')%>% 
  select(Country, country_CO2_tons_per_capita = Value)
```

```{r}
species <-
  UN %>% 
  filter(topic == 'threatened species' & Series == 'Threatened Species: Total (number)')%>% 
  select(Country, country_threatened_species_total_num = Value)
```

```{r}
education <-
  UN %>% 
  filter(topic == 'expenditure on edu' & Series == 'Public expenditure on education (% of GDP)')%>% 
  select(Country, country_edu_exp_as_GDP_percentage = Value)
```

```{r}
health <-
  UN %>% 
  filter(topic == 'expenditure on health' & Series == 'Current health expenditure (% of GDP)')%>% 
  select(Country, country_health_exp_as_GDP_percentage = Value)
```

```{r}
internet <-
  UN %>% 
  filter(topic == 'internet usage' & Series == 'Percentage of individuals using the internet')%>% 
  select(Country, country_individuals_using_internet_percentage = Value)
```

```{r}
land <-
  UN %>% 
  filter(topic == 'land' & Series == 'Land area (thousand hectares)')%>% 
  select(Country, country_land_area_thousand_hectars = Value)
```

```{r}
migrants <-
  UN %>% 
  filter(topic == 'migrants' & Series == 'International migrant stock: Both sexes (% total population)')%>% 
  select(Country, country_international_migrants_population_percentage = Value)

```

```{r}
tourism <-
  UN %>% 
  filter(topic == 'tourism' & Series == 'Tourist/visitor arrivals (thousands)')%>% 
  select(Country, country_tourists_thousand = Value)
```

```{r}
population <-
  UN %>% 
  filter(topic == 'population' & Series == 'Population mid-year estimates (millions)')%>% 
  select(Country, country_population_millions = Value)
```

```{r}
UN_combined <-
  full_join(GDP, RD) %>% 
  full_join(CO2) %>% 
  full_join(species) %>% 
  full_join(education) %>% 
  full_join(health) %>% 
  full_join(internet) %>% 
  full_join(land) %>% 
  full_join(migrants) %>% 
  full_join(tourism) %>% 
  full_join(population) 
#, CO2, species, education, health, internet, land, migrants, tourism, population)

```




```{r}
UN_UNESCO <- right_join(UN_combined, UNESCO, on = 'Country')
```
```{r}
write.csv(UN_UNESCO,'../data/UN_UNESCO.csv')
```

```{r}
UN_UNESCO <- 
  rename(UN_UNESCO, c('location_description' = 'Description of the location', 
                      'english_name' = 'Name in English',
                      'french_name' = 'Name in French',
                      'spanish_name' = 'Name in Spanish',
                      'ISO639-3_codes' = 'ISO639-3 codes',
                      'endangerment_degree' = 'Degree of endangerment', 
                      'alternate_names' = 'Alternate names', 
                      'name_in_the_language' = 'Name in the language', 
                      'number_of_speakers' = 'Number of speakers'))

```


```{r}
library(sf)
library(leaflet)
library(htmltools)
```

```{r}
UN_UNESCO <- UN_UNESCO %>%
  mutate(endangerment_degree = factor(endangerment_degree, 
                                      levels = c("Vulnerable",
                                                 "Definitely endangered",
                                                 "Severely endangered", 
                                                 "Critically endangered",
                                                 "Extinct")))
```


```{r}
critical <- UN_UNESCO %>% 
  filter(endangerment_degree == 'Critically endangered')
definite <- UN_UNESCO %>% 
  filter(endangerment_degree == 'Definitely endangered')
extinct <- UN_UNESCO %>% 
  filter(endangerment_degree == 'Extinct')
severe <- UN_UNESCO %>% 
  filter(endangerment_degree == 'Severely endangered')
vulnerable <- UN_UNESCO %>% 
  filter(endangerment_degree == 'Vulnerable')
```


```{r}

pal <- colorFactor(palette = c('navajowhite2', 'yellow', 'orange', 'red', 'black'), 
                   levels = c("Vulnerable",
                              "Definitely endangered",
                              "Severely endangered", 
                              "Critically endangered",
                              "Extinct"))
make_popups <- function(dataframe){
  
  popup <- paste("<b>English name:</b>", dataframe$english_name,"<br>",
                 "<b>French name:</b>", dataframe$french_name,"<br>",
                 "<b>Spanish name:</b>", dataframe$spanish_name, "<br>",
                 
                 "<b>ISO639-3 code:</b>", dataframe$`ISO639-3_codes`,"<br>",
                 "<b>Alternate name:</b>", dataframe$alternate_names,"<br>",
                 "<b>Endangerment degree:</b>", dataframe$endangerment_degree,"<br>",
                 "<b>Number of speakers:</b>", dataframe$number_of_speakers,"<br>",
                 "<b>Country:</b>", dataframe$Country,"<br>",
                 
                 "<b>Specific location(s):</b>",  dataframe$location_description,"<br>"
  )
return(popup)
  }

#make_popups(UN_UNESCO)



leaflet() %>% 
  addProviderTiles(provider = "Esri") %>% 
  
  addCircleMarkers(data = vulnerable, radius = log10(vulnerable$number_of_speakers), opacity = .6, color = pal(vulnerable$endangerment_degree), group = 'Vulnerable',
                   lng = ~Longitude, 
                   lat = ~Latitude,
                   popup = make_popups(vulnerable))  %>%
  
  addCircleMarkers(data = definite, radius = log10(definite$number_of_speakers), opacity = .6, color = pal(definite$endangerment_degree), group = 'Definitely endangered',
                   lng = ~Longitude, 
                   lat = ~Latitude,
                   popup = make_popups(definite))  %>%
  
  addCircleMarkers(data = critical, radius = log10(critical$number_of_speakers), opacity = .6, color = pal(critical$endangerment_degree), group = 'Critically endangered',
                   lng = ~Longitude, 
                   lat = ~Latitude,
                   popup = make_popups(critical))  %>%
  
  addCircleMarkers(data = severe, radius = log10(severe$number_of_speakers), opacity = .6, color = pal(severe$endangerment_degree), group = 'Severely endangered',
                   lng = ~Longitude, 
                   lat = ~Latitude,
                   popup = make_popups(severe))  %>%
  
  addCircleMarkers(data = extinct, radius = log10(extinct$number_of_speakers), opacity = .6, color = pal(extinct$endangerment_degree), group = 'Extinct',
                   lng = ~Longitude, 
                   lat = ~Latitude,
                   popup = make_popups(extinct))  %>%
  
  addLayersControl(overlayGroups = c('Vulnerable', 'Definitely endangered', 'Critically endangered', 'Severely endangered', 'Extinct')) %>% 
  addLegend(pal = pal, position = 'bottomright', values = factor(UN_UNESCO$endangerment_degree), title = 'Endangerment degrees' 
  )
```


```{r}
UN_UNESCO %>% 
  group_by(endangerment_degree) %>% 
  count() %>% 
  arrange(desc(n))
```



```{r}
UN_UNESCO <- 
  UN_UNESCO %>% 
  mutate(vitality_level = case_when(
    endangerment_degree == 'Exticnt' ~ 1,
    endangerment_degree == 'Critically endangered' ~ 2,
    endangerment_degree == 'Severely endangered' ~ 3,
    endangerment_degree == 'Definitely endangered' ~ 4,
    endangerment_degree == 'Vulnerable' ~ 5))
```

```{r}
UN_UNESCO <- 
  UN_UNESCO %>% 
  group_by(Country) %>% 
  mutate(vitality_level_mean = mean(vitality_level, na.rm = T))
```

```{r}
UN_UNESCO %>% 
  group_by(Country) %>% 
ggplot(aes(y =country_GDP_per_capita_US_dollars, x = vitality_level_mean, colour = )) +
  geom_point() 
```


```{r}
g_languages <- read_csv('../data/glottolog_languages.csv')
g_areas <- read_csv('../data/glottolog_areas.csv')
g_families <- read_csv('../data/glottolog_families.csv')
```

```{r}
glottolog <- 
  full_join(g_languages, g_areas, by = 'english_name') %>% 
  full_join(g_families, by = 'family_id')
```

```{r}
glottolog <- select(glottolog, -'family_id')
```


```{r}
UN_UNESCO <- left_join(UN_UNESCO, glottolog)
```


```{r}
a<- UN_UNESCO %>% 
  ggplot(aes(fill = as_factor(country_GDP_per_capita_US_dollars), x = endangerment_degree)) +
  geom_bar(position='fill') +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE))
ggplotly(a)
```


